name: '${name}'
version: '${version}'
main: com.balugaq.bim.MyPluginMain
api-version: '1.20'
depend: []
softdepend: []
loadBefore: []
authors: [balugaq]
description: ""
commands:
  bim:
    description: /bim
    usage: /bim
permissions:
  bim:
    description: Big Interaction Menu's main command
    default: op