[versions]
shadow = "9.3.2"
paper = "1.21.11-R0.1-SNAPSHOT"
lombok = "1.18.46"
junit = "5.11.4"
mockito = "5.14.2"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
libby-bukkit = { module = "net.byteflux:libby-bukkit", version = "1.3.1" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }